# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildanddeploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.3.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: ci
      run: npm ci
    - name: build
    - run: npm run build --if-present
    - name: clone remote
      run: git clone https://github.com/usamakhalidxo0/ci-cd.git .
    - name: add heroku
      env:
       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: git remote add heroku https://heroku:a9855ac6-ed01-4106-87b3-99cdb40acb2b@git.heroku.com/ci-cd-proj.git
    - name: push remote
      env:
       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: git push heroku master
        
    
