# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.3.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: init
        run: ls -a
      - name: pwd
        run: pwd
      - name: add remote
        run: git clone https://github.com/usamakhalidxo0/ci-cd.git .
      - name: ls
        run: ls -a
      - name: pwd
        run: pwd
      - name: add heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: git remote add heroku https://heroku:${{ secrets.heroku_api_key }}@git.heroku.com/${{ secrets.heroku_app_name }}.git
      - name: push remote
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: git push heroku master
